21:05:17 ERROR Workflow.Action.InputField Workflow::Exception (63) configuration_error exception thrown from [Workflow::Action::InputField: 39; before: main: 13]: Field found without name: [] 
21:05:17 DEBUG Workflow.Action.InputField Workflow::Action::InputField (22) Instantiating new field 'test' 
21:05:17 DEBUG Workflow.Action.InputField Workflow::Action::InputField (22) Instantiating new field 'test' 
21:05:17 DEBUG Workflow.Action.InputField Workflow::Action::InputField (22) Instantiating new field 'test' 
